GET https://riot:AvgOeCnPbvhl6GSRKeWZzQ@127.0.0.1:51491/lol-career-stats/v1/summoner-games/t98zb5-DNQNNLYnLi82-fQwZsXjQ79d7_we2jUbKZSxfb4Oj7eSwg2fN2aVfg3qiBnevyPkiK8fcLw

###
GET https://riot:AvgOeCnPbvhl6GSRKeWZzQ@127.0.0.1:51491/lol-trophies/v1/current-summoner/trophies/profile